name: Benchmarks

concurrency:
  group: benchmark-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  benchmarks:
    strategy:
      fail-fast: false
      matrix:
        crate: [fluvio-protocol, fluvio-smartmodule]
    runs-on: ubuntu-latest
    name: Fluvio Benchmarks  ${{ matrix.crate }}
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Cache Rust Cargo files
        uses: Swatinem/rust-cache@v2
        with:
          # Additional non workspace directories, separated by newlines
          key: benches-${{ runner.os }}-${{ matrix.crate }}

      - name: Run Benchmarks
        run: cargo bench -p ${{ matrix.crate }} -- --output-format bencher | tee output.txt

      - name: Save base benchmark
        uses: morenol/github-action-benchmark@v1
        with:
          tool: cargo
          output-file-path: output.txt
          external-data-json-path: ./benchmark-data.json
          read-commit-id-from-git: true

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          clean: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Benchmarks
        run: cargo bench -p ${{ matrix.crate }} -- --output-format bencher | tee output.txt

      - name: Check benchmark
        uses: morenol/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: "cargo"
          # Where the output from the benchmark tool is stored
          output-file-path: output.txt
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Leave a commit comment comparing the current branch with the previous
          comment-always: true
          # Result from running this on master
          external-data-json-path: ./benchmark-data.json
          # Mention @infinyon/developers in the commit comment
          alert-comment-cc-users: "@infinyon/developers"
